language:
  - cpp
  - python
  - bash

install:
  - sudo apt-get install libvtk5-dev

python:
  - "2.7"

addons:
  apt:
    packages:
      - cmake

script:
  - bash configure.sh
  - cd tests
  - bash run_tests.sh
  - cd ..
  - echo "Done!"
