# Configuration file for Travis-CI
##################################

language:
  - cpp
  - python
  - bash

python:
  - "3"

addons:
    packages:
      - cmake

script:
  - bash install.sh
  - bash build.sh minimal
  - cd tests
  - bash run_tests.sh
