# Configuration file for Travis-CI
##################################

os:
  - osx
  - linux

language:
  - cpp
  - python
  - bash

python:
  - "3.7"

addons:
    packages:
      - cmake

script:
  - bash install.sh
  - bash build.sh
#  - cd tests
#  - bash run_tests.sh
