name: magritte_env
channels:
  - bokeh
  - anaconda
  - conda-forge
  - http://conda.binstar.org/erik
  - defaults
dependencies:
  - backcall=0.1.0
  - bleach=3.1.0
  - decorator=4.4.0
  - defusedxml=0.5.0
  - entrypoints=0.3
  - gmp=6.1.2
  - h5py=2.9.0
  - hdf5=1.10.4
  - ipykernel=5.1.0
  - ipython=7.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - libsodium=1.0.16
  - mistune=0.8.4
  - nbconvert=5.4.1
  - nbformat=4.4.0
  - notebook=5.7.8
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.4
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pygments=2.3.1
  - pyrsistent=0.14.11
  - pyzmq=18.0.0
  - qtconsole=4.4.3
  - send2trash=1.5.0
  - terminado=0.8.1
  - testpath=0.4.2
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - widgetsnbextension=3.4.2
  - zeromq=4.3.1
  - bokeh=1.1.0
  - astropy=3.1.2
  - atk=2.25.90
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - cairo=1.14.12
  - certifi=2019.3.9
  - cycler=0.10.0
  - expat=2.2.5
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gdk-pixbuf=2.36.12
  - gettext=0.19.8.1
  - glib=2.56.2
  - gobject-introspection=1.56.1
  - graphite2=1.3.13
  - gtk2=2.24.31
  - harfbuzz=1.9.0
  - healpy=1.12.9
  - icu=58.2
  - jpeg=9c
  - kiwisolver=1.0.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libiconv=1.15
  - liblapack=3.8.0
  - libpng=1.6.36
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - more-itertools=4.3.0
  - ncurses=6.1
  - numpy=1.16.2
  - openblas=0.3.5
  - openssl=1.1.1b
  - pango=1.40.14
  - pip=19.0.3
  - pixman=0.34.0
  - pluggy=0.9.0
  - psutil=5.6.1
  - pthread-stubs=0.4
  - py=1.8.0
  - pyparsing=2.4.0
  - pyqt=5.6.0
  - pytest=4.4.0
  - pytest-arraydiff=0.3
  - pytest-astropy=0.5.0
  - pytest-doctestplus=0.3.0
  - pytest-openfiles=0.3.1
  - pytest-remotedata=0.3.1
  - pytest-runner=4.4
  - python=3.7.3
  - python-dateutil=2.8.0
  - readline=7.0
  - scipy=1.2.1
  - setuptools=41.0.0
  - sip=4.18.1
  - six=1.12.0
  - sqlite=3.26.0
  - tk=8.6.9
  - tornado=6.0.2
  - wheel=0.33.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.7
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - zlib=1.2.11
  - libgfortran=3.0.0
  - dbus=1.13.2
  - futures-compat=1.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - jinja2=2.10
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=8.2.0
  - markupsafe=1.1.1
  - olefile=0.46
  - packaging=19.0
  - pcre=8.43
  - pillow=5.4.1
  - pyyaml=5.1
  - qt=5.6.3
  - yaml=0.1.7
