# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/frederik/Dropbox/Astro/3D-RT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/frederik/Dropbox/Astro/3D-RT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/frederik/Dropbox/Astro/3D-RT/CMakeFiles /home/frederik/Dropbox/Astro/3D-RT/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/frederik/Dropbox/Astro/3D-RT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 3D-RT

# Build rule for target.
3D-RT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 3D-RT
.PHONY : 3D-RT

# fast build rule for target.
3D-RT/fast:
	$(MAKE) -f CMakeFiles/3D-RT.dir/build.make CMakeFiles/3D-RT.dir/build
.PHONY : 3D-RT/fast

#=============================================================================
# Target rules for targets named _3DRT

# Build rule for target.
_3DRT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _3DRT
.PHONY : _3DRT

# fast build rule for target.
_3DRT/fast:
	$(MAKE) -f src/CMakeFiles/_3DRT.dir/build.make src/CMakeFiles/_3DRT.dir/build
.PHONY : _3DRT/fast

#=============================================================================
# Target rules for targets named _HEALPix

# Build rule for target.
_HEALPix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _HEALPix
.PHONY : _HEALPix

# fast build rule for target.
_HEALPix/fast:
	$(MAKE) -f src/HEALPix/CMakeFiles/_HEALPix.dir/build.make src/HEALPix/CMakeFiles/_HEALPix.dir/build
.PHONY : _HEALPix/fast

#=============================================================================
# Target rules for targets named _sundials

# Build rule for target.
_sundials: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _sundials
.PHONY : _sundials

# fast build rule for target.
_sundials/fast:
	$(MAKE) -f src/sundials/CMakeFiles/_sundials.dir/build.make src/sundials/CMakeFiles/_sundials.dir/build
.PHONY : _sundials/fast

src/3D-RT.o: src/3D-RT.cpp.o

.PHONY : src/3D-RT.o

# target to build an object file
src/3D-RT.cpp.o:
	$(MAKE) -f CMakeFiles/3D-RT.dir/build.make CMakeFiles/3D-RT.dir/src/3D-RT.cpp.o
.PHONY : src/3D-RT.cpp.o

src/3D-RT.i: src/3D-RT.cpp.i

.PHONY : src/3D-RT.i

# target to preprocess a source file
src/3D-RT.cpp.i:
	$(MAKE) -f CMakeFiles/3D-RT.dir/build.make CMakeFiles/3D-RT.dir/src/3D-RT.cpp.i
.PHONY : src/3D-RT.cpp.i

src/3D-RT.s: src/3D-RT.cpp.s

.PHONY : src/3D-RT.s

# target to generate assembly for a file
src/3D-RT.cpp.s:
	$(MAKE) -f CMakeFiles/3D-RT.dir/build.make CMakeFiles/3D-RT.dir/src/3D-RT.cpp.s
.PHONY : src/3D-RT.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 3D-RT"
	@echo "... _3DRT"
	@echo "... _HEALPix"
	@echo "... _sundials"
	@echo "... src/3D-RT.o"
	@echo "... src/3D-RT.i"
	@echo "... src/3D-RT.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

