#! /bin/bash


NUMBER_OF_PROCESSES=1
NUMBER_OF_THREADS=1 
FLAG_FOR_SHARED_MEM='-env I_MPI_SHM_LMT shm'
PATH_TO_EXECUTABLE='build/examples/example_Lines_Lime1.exe'

export OMP_NUM_THREADS=$NUMBER_OF_THREADS

mpirun -np $NUMBER_OF_PROCESSES $FLAG_FOR_SHARED_MEM $PATH_TO_EXECUTABLE
