// Generated by setup.py

#define OUTPUT_DIRECTORY "/home/frederik/Dropbox/Astro/MagritteProjects/Lime_1/output/files/18-04-22_16:11:59/"

#define PROJECT_FOLDER "/home/frederik/Dropbox/Astro/MagritteProjects/Lime_1/"

