// Generated by setup.py

#ifndef __LINEDATA_CONFIG_HPP_INCLUDED__
#define __LINEDATA_CONFIG_HPP_INCLUDED__

#define NSPEC 5

#define NLSPEC 1

#define NLEV {6}

#define NRAD {5}

#define NCOLPAR {0}

#define NCOLTEMP {{0}}

#define NCOLTRAN {{0}}

#define NUMBER {1}

#define NAME {"test"}

#define PARTNER_NR {{0}}

#define ORTHO_PARA {{'n'}}

#define ENERGY {{0.0, 1.0, 2.0, 3.0, 4.0, 5.0}}

#define WEIGHT {{1, 1, 1, 1, 1, 1}}

#define IRAD {{1, 2, 3, 4, 5}}

#define JRAD {{0, 1, 2, 3, 4}}

#define FREQ {{1.0, 2.0, 3.0, 4.0, 5.0}}

#define A_COEFF

#define B_COEFF

#define ICOL

#define JCOL

#define COLTEMP

#define C_DATA


#endif // __LINEDATA_CONFIG_HPP_INCLUDED__
