# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# compile CXX with /opt/intel/compilers_and_libraries_2017/linux/bin/intel64/icc
CXX_FLAGS =  -qopenmp  

CXX_DEFINES = 

CXX_INCLUDES = 

