// Generated by setup.py

#define OUTPUT_DIRECTORY "/home/frederik/Dropbox/Astro/MagritteProjects/3DPDR/output/files/18-04-11_14:02:11/"

#define PROJECT_FOLDER "/home/frederik/Dropbox/Astro/MagritteProjects/3DPDR/"

