// Generated by setup.py

#define OUTPUT_DIRECTORY "/home/frederik/Dropbox/Astro/MagritteProjects/3DPDR/output/files/18-04-10_15:07:53/"

#define PROJECT_FOLDER "/home/frederik/Dropbox/Astro/MagritteProjects/3DPDR/"

