// Generated by setup.py

#define OUTPUT_DIRECTORY "/home/frederik/Dropbox/Astro/Magritte/tests/integration_tests/chemistry/output/files/18-04-10_12:34:09/"

#define PROJECT_FOLDER "/home/frederik/Dropbox/Astro/Magritte/tests/integration_tests/chemistry/"

